#ifndef CONFIG_ESP
#define CONFIG_ESP

#define WIFI_SSID "YOUR_SSID"
#define WIFI_PASSWORD "YOUR_PASSWORD"

#define MQTT_SERVER "YOUR_SERVER_MQTT"
#define MQTT_PORT 1883
#define MQTT_USER "YOUR_USER_MQTT"
#define MQTT_PASSWORD "YOUR_PASSWORD_MQTT"

#endif
